djangopi/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

djangopi/djangopi/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from homeinfo.applications.watersystem import WateringSystem
import threading

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("thanks/", views.ThanksPage.as_view(), name="thanks"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("homeinfo/", include("homeinfo.urls", namespace="homeinfo")),
]

# watersys = WateringSystem()
# thread_watersystem = threading.Thread(target=watersys.run)
# thread_watersystem.start()

djangopi/homeinfo/urls.py
from django.urls import path
from . import views

app_name = "homeinfo"

urlpatterns = [
    path("", views.DashBoard.as_view(), name="dashboard"),
    path("update_toggle/", views.update_toggle, name="update_toggle"),
    path("update_page/", views.update_page, name="update_page"),
]

djangopi/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.


class User(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return self.username

djangopi/games/models.py
from django.db import models

# Create your models here.

djangopi/homeinfo/models.py
from django.db import models

# Create your models here.
class ToggleWatering(models.Model):
    auto = models.BooleanField(default=False)
    manual = models.BooleanField(default=False)

    def __str__(self):
        return "Auto: {}, Manual: {}".format(self.auto, self.manual)


class Log(models.Model):
    log = models.TextField()
    time_watered = models.DateTimeField()

    def __str__(self):
        return self.log

djangopi/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display Name"
        self.fields["email"].label = "Email Address"

djangopi/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms

# Create your views here.


class SignUp(CreateView):
    form_class = forms.UserCreateForm
    template_name = "accounts/signup.html"

    def get_success_url(self):
        return reverse_lazy("login")

djangopi/djangopi/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = "index.html"


class ThanksPage(TemplateView):
    template_name = "thanks.html"

djangopi/games/views.py
from django.shortcuts import render

# Create your views here.

djangopi/homeinfo/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from braces.views import SuperuserRequiredMixin, LoginRequiredMixin
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

from .models import ToggleWatering, Log

# Create your views here.
class DashBoard(SuperuserRequiredMixin, TemplateView):
    template_name = "homeinfo/dashboard.html"

    def get_context_data(self, **kwargs):
        self.toggles = ToggleWatering.objects.filter().first()
        log_items = Log.objects.filter().order_by("time_watered")[:16]
        context = super().get_context_data(**kwargs)
        context["manual"] = ": checked" if self.toggles.manual else ""
        context["auto"] = ": checked" if self.toggles.auto else ""
        context["log"] = [
            str(item.log).ljust(10, "-")
            + item.time_watered.strftime("%d-%b-%Y %H:%M:%S")
            for item in log_items
        ]
        return context


@login_required
def update_toggle(request):
    toggles = ToggleWatering.objects.filter().first()
    if request.is_ajax() and request.method == "POST":
        button = request.POST.get("button")
        b_change = request.POST.get("change")
        if button == "manual":
            if b_change == "on":
                toggles.manual = True
                toggles.save()
            else:
                toggles.manual = False
                toggles.save()
        else:
            if b_change == "on":
                toggles.auto = True
                toggles.save()
            else:
                toggles.auto = False
                toggles.save()
        return JsonResponse({"button": button, "change": b_change}, status=200)
    return JsonResponse({"error": ""}, status=400)


@login_required
def update_page(request):
    toggles = ToggleWatering.objects.filter().first()
    log_items = Log.objects.filter().order_by("time_watered")[:16]
    response_data = {}
    response_data["manual"] = toggles.manual
    response_data["auto"] = toggles.auto
    response_data["log"] = [
        str(item.log).ljust(10, "-") + item.time_watered.strftime("%d-%b-%Y %H:%M:%S")
        for item in log_items
    ]
    return JsonResponse(response_data)

djangopi/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title%}
Log In
{% endblock title %}

{% block content %}
<div class="bg">
    <div class="container">
        <div class="jumbotron">
            <h1>Please Login</h1>
            <form method="POST">
                {% csrf_token %}
                {% bootstrap_form form%}
                <input type="submit" class="btn btn-primary" value='Log In'>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

djangopi/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title%}
Sign Up
{% endblock title %}

{% block content %}
<div class="bg">
    <div class="container">
        <div class="jumbotron">
            <h1>Sign Up</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form%}
                <input type="submit" class="btn btn-primary" value='Log In'>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

djangopi/homeinfo/templates/homeinfo/dashboard.html
{% extends 'base.html' %}
{%load static%}
{%block title%}
Dashboard
{%endblock title%}
{%block style%}
<link href="{% static 'css/dashboard.css'%}" rel="stylesheet">
{% endblock style %}
{% block content %}
{% csrf_token %}
<div class="bg">
    <div class="container">
        <div class="jumbotron">
            <legend> Watering System</legend>
            <div class="row">
                <div class="col-md-6">
                    <h5>Toggle Auto Watering</h5><br>
                    <label class=" switch">
                        <input type="checkbox" id='Auto' {{auto}}>
                        <span class="slider"></span>
                    </label>
                </div>
                <div class="col-md-6 ml-auto">
                    <h5>Manually Water</h5><br>
                    <label class="switch">
                        <input type="checkbox" id='Manual' {{manual}}>
                        <span class="slider"></span>
                    </label>
                </div>
            </div>
            <div class="text-center">
                <button class="btn dropdown-toggle btn-primary btn-sm" data-toggle="dropdown">Data Log
                    <span class="caret"></span></button>
                <ul class="dropdown-menu" , style="height:40%; overflow:hidden; overflow-y:scroll;">
                    {% for item in log %}
                    <li>{{item}}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content%}

{% block javascript %}
<script>
    csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    $(document).ready(function () {
        $("#Auto").on('change', function () {
            event.preventDefault();
            if ($(this).is(':checked')) {
                $.ajax({
                    headers: { 'X-CSRFToken': csrftoken },
                    type: "POST",
                    url: "{% url 'homeinfo:update_toggle'%}",
                    data: { "button": "auto", "change": "on" },
                    success: function (response) {
                        console.log("Toggle change sent successfully")
                    },
                    error: function (response) {
                        alert(response["responseJSON"]["error"]);
                    }
                })

            }
            else {
                $.ajax({
                    headers: { 'X-CSRFToken': csrftoken },
                    type: "POST",
                    url: "{% url 'homeinfo:update_toggle'%}",
                    data: { "button": "auto", "change": "off" },
                    success: function (response) {
                        console.log("Toggle change sent successfully")
                    },
                    error: function (response) {
                        alert(response["responseJSON"]["error"]);
                    }
                })
            }
        });

        $("#Manual").on('change', function () {
            event.preventDefault();
            if ($(this).is(':checked')) {
                $.ajax({
                    headers: { 'X-CSRFToken': csrftoken },
                    type: "POST",
                    url: "{% url 'homeinfo:update_toggle'%}",
                    data: { "button": "manual", "change": "on" },
                    success: function (response) {
                        console.log("Toggle change sent successfully")
                    },
                    error: function (response) {
                        alert(response["responseJSON"]["error"]);
                    }
                })
            }
            else {
                $.ajax({
                    headers: { 'X-CSRFToken': csrftoken },
                    type: "POST",
                    url: "{% url 'homeinfo:update_toggle'%}",
                    data: { "button": "manual", "change": "off" },
                    success: function (response) {
                        console.log("Toggle change sent successfully")
                    },
                    error: function (response) {
                        alert(response["responseJSON"]["error"]);
                    }
                })
            }
        });
    })
</script>
<script>
        (function worker() {
            $.ajax({
                url: "{% url 'homeinfo:update_page'%}",
                success: function (data) {
                    if (data.manual == false) {
                        $('#Manual').prop('checked', false);
                    } else {
                        $('#Manual').prop('checked', true)
                    }
                    if (data.auto == false) {
                        $('#Auto').prop('checked', false);
                    } else {
                        $('#Auto').prop('checked', true);
                    }
                    if (data.log) {
                        var logs = ""
                        for (item of data.log) {
                            logs += "<li>" + item + "</li>"
                        }
                        $(".dropdown-menu").html(logs)
                    }
                },
                complete: function () {
                    // Schedule the next request when the current one's complete
                    setTimeout(worker, 5000);
                }
            });
        })();
</script>
{% endblock javascript%}

djangopi/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%}{%endblock title%}</title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/lp.css'%}" rel="stylesheet">
    {%block style%}
    {% endblock style %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">DjangoPi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            {% if not user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{%url 'accounts:signup'%}"><span
                            class="glyphicon glyphicon-user"></span>
                        Register</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login'%}"><span
                            class="glyphicon glyphicon-log-in"></span> Login</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="#">Games</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'homeinfo:dashboard'%}">Home Info</a></li>
            </ul>
            <ul class=" navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a></li>
            </ul>
            <span class="navbar-text">{{user.username}}</span>
            {% endif %}
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <footer class="footer mt-auto py-3">
        <div class="container">
            <span class="text-muted">https://github.com/EdwinIngJ</span>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    {% block javascript %}
    {% endblock javascript%}
</body>

</html>

djangopi/templates/index.html
{% extends "base.html" %}
{% block title%}
Index
{% endblock title %}

{% block content %}
<div class="bg">
    <div class="container">
        <div class="jumbotron">
            <h1>This is the index!</h1>
        </div>
    </div>
</div>
{% endblock %}

djangopi/templates/thanks.html
{%extends "base.html"%}
{% block title%}
Logout
{% endblock title %}
{% block content %}
<div class="bg">
    <div class="container">
        <div class="jumbotron">
            <h1>Thanks for visiting!</h1>
        </div>
    </div>
</div>
{% endblock %}